### ISSUE TITLE
KeyError:'meta'

### ISSUE THREAD

**Issue by Morphling89** [neptune-ml/kaggle-toxic-starter#36]
HI, I just pull out the master branch code and run the experiment without changing anything. But still has this problem: 
2018-03-13 21-02-21 toxic >>> Training...
2018-03-13 21-02-21 toxic >>> step xy_train adapting inputs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
    execute()
  File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
    execfile(job_filepath, job_globals)
  File "/usr/local/lib/python3.6/dist-packages/past/builtins/misc.py", line 82, in execfile
    exec_(code, myglobals, mylocals)
  File "main.py", line 382, in <module>
    action()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 255, in train_evaluate_predict_cv_pipeline
    pipeline_name)
  File "main.py", line 311, in _fold_fit_loop
    _ = pipeline.fit_transform(data_train)
  File "/neptune/steps/base.py", line 71, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/neptune/steps/base.py", line 71, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/neptune/steps/base.py", line 71, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/neptune/steps/base.py", line 74, in fit_transform
    step_inputs = self.adapt(step_inputs)
  File "/neptune/steps/base.py", line 153, in adapt
    raw_inputs = [step_inputs[step_name][step_var] for step_name, step_var in step_mapping]
  File "/neptune/steps/base.py", line 153, in <listcomp>
    raw_inputs = [step_inputs[step_name][step_var] for step_name, step_var in step_mapping]
KeyError: 'meta'

I use pip3 and install all package in the requirement, so did I do it wrong? or could you please fix this?
Thank you

**Comment by jakubczakon** [comment]
When training first level models with `train_evaluate_predict_cv_piepeline` you need to pass `--model_level first` . 
It wasn't explained in the wiki as we were previously using `train_evaluate_predict_pipeline`.
Now the wiki is updated and I think it should work just fine.
Will test it tomorrow.
